# Generated by Django 5.1.7 on 2025-04-04 12:27

from django.db import migrations
def capitalize(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    for product in Product.objects.all():
        product.name = product.name.capitalize()
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productimage_thumbnail'),
    ]

    operations = [
        migrations.RunPython(
        capitalize, # Forward function
        migrations.RunPython.noop # Backward function (does nothing)
        ),
    ]
